# docker-compose.yml
services:
  mysql:
    image: mysql:8
    container_name: poll_mysql
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306" # Workbench access
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis: 
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  app:
    build: .
    container_name: poll_app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: "service_started"
    environment:
      # DB for app
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myapp?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # Tells rediscache where redis lives
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"

volumes:
  mysql_data: